"""generate tables

Revision ID: 7abe104912c1
Revises: 
Create Date: 2022-12-30 20:18:30.045198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abe104912c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_complete', sa.String(), nullable=False),
    sa.Column('solution', sa.String(), nullable=False),
    sa.Column('dialogue', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('to_complete')
    )
    op.create_table('jumbles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_word_id'], ['master_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jumble_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jumble_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('defs', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('placeholder', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['jumble_id'], ['jumbles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jumble_options')
    op.drop_table('jumbles')
    op.drop_table('master_words')
    # ### end Alembic commands ###
